import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { DynamicContextProvider, DynamicWidget } from '@dynamic-labs/sdk-react-core';
import { EthereumWalletConnectors } from "@dynamic-labs/ethereum";


const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <DynamicContextProvider
        settings={{
          environmentId: '00c53e02-4ff3-4fb8-8c30-bed88a24b8ce',
          walletConnectors: [ EthereumWalletConnectors ],
        }}>
            {children}
        </DynamicContextProvider>
      </body>
    </html>
  );
}
