import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { DynamicContextProvider, DynamicWidget } from '@dynamic-labs/sdk-react-core';
import { EthereumWalletConnectors } from "@dynamic-labs/ethereum";


const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const evmNetworks = [
  {
  blockExplorerUrls: ['https://explorer.helium.fhenix.zone'],
  chainId: 1,
  chainName: 'Fhenix Helium Testnet',
  iconUrls: ['https://docs.fhenix.zone/img/logo-white.svg'],
  name: 'Helium',
  nativeCurrency: {
  decimals: 18,
  name: 'tFHE',
  symbol: 'tFHE',
  },
  networkId: 1,
  rpcUrls: ['https://api.helium.fhenix.zone'],
  vanityName: 'Fhenix Helium',
  },
  // Add more custom networks here
  ];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <DynamicContextProvider
        settings={{
          environmentId: '00c53e02-4ff3-4fb8-8c30-bed88a24b8ce',
          walletConnectors: [ EthereumWalletConnectors ],
          overrides: { evmNetworks },
        }}>
            {children}
        </DynamicContextProvider>
      </body>
    </html>
  );
}
